### ISSUE TITLE
ID generator

### ISSUE THREAD

**Issue by shaharkamay** [DanielPhilosoph/Cyber4S-openFullStack#3]
Great job!
in these lines I see that your limit of IDs is 1000 and I think you need a bigger number.
https://github.com/DanielPhilosoph/Cyber4S-openFullStack/blob/53499f18b44a773602ddfc24beed77265e54343d/routers/presons.js#L55-L57

**Comment by DanielPhilosoph** [comment]
Great! Fixed it to 10,000
